// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytqwrhwywyjbkrebibkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cXdyaHd5d3lqYmtyZWJpYmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjgxNDgsImV4cCI6MjA3MTIwNDE0OH0.x_-xT48OTz3QayyDcJ2u_boP6wY-2RRP1UDGQWxcT6Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});